# (c) 2016 DataNexus Inc.  All Rights Reserved.
#
# example AWS instance
---
cloud: aws  
tenant: TENANT
project: PROJECT
domain: DOMAIN
region: REGION
zone: ZONE
cidr_block: CIDR_BLOCK
internal_subnet: SUBNET
external_subnet: SUBNET
