# (c) 2016 DataNexus Inc.  All Rights Reserved.
#
# example AWS instance
---
cloud: aws  
tenant: datanexus
project: demo
domain: development
region: us-east-1
zone: a
cidr_block: 10.10.0.0/16
internal_subnet: 10.10.1.0/24
external_subnet: 10.10.2.0/24
